### ISSUE TITLE
Alpha channel

### ISSUE THREAD

**Issue by djaax** [Wondermarin/react-color-palette#10]
### The Problem:

Users are unable to modify the alpha channel / opacity of colors.

### The Solution:

Add alpha channel / opacity slider.

### Additional Context:

Awesome work. Just wondering if you plan to implement an alpha channel slider or anything similar.

**Comment by Wondermarin** [comment]
Hello, thank you for your feedback, yes, I plan to add it, but the fact is that I do not have enough time at the moment, so I would be very grateful if you could make a pull request.

**Comment by Hawkbat** [comment]
I took a stab at implementing it, if you want to look it over / build on it:
https://github.com/Wondermarin/react-color-palette/pull/15
