### ISSUE TITLE
Hue bar depends on hide props

### ISSUE THREAD

**Issue by DraGonM** [Wondermarin/react-color-palette#12]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| react             | 16.8.6   |
| react-color-palette | 5.0.0   |

### Expected Behavior:

Hue bar allows correct selection of hue even with `hideHSB` enabled

### Actual Behavior:
It seems hue bar depends on props `hideHSB, hideHEX, hideRGB` in terms of width, because of this we have an incorrect selection of hue when we remove one of the format field, as you can see in the screenshot below
![image](https://user-images.githubusercontent.com/17852469/120629228-451e6a80-c46e-11eb-9550-9d52ce2f9f25.png)
`hideHSB` enabled

Thx for great and light library = )

**Comment by Wondermarin** [comment]
Hi, thank you for your feedback, I'll fix this in the next update. <3

**Comment by Wondermarin** [comment]
Should be fixed in 6.0.0
