### ISSUE TITLE
hideHSB, not hideHSV

### ISSUE THREAD

**Issue by wmhartl** [Wondermarin/react-color-palette#14]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | vX.Y.Z   |
| react-color-palette version | vX.Y.Z   |

### Expected Behavior:

according to the documentation:
hideHSV | bool | false | Hide HSV input.

example given:
      <ColorPicker width={456} height={228} color={color} onChange={setColor} hideHSV dark />

### Actual Behavior:

The hideHSV prop does not work; hideHSB does work:
      <ColorPicker width={456} height={228} color={color} onChange={setColor} hideHSB dark />

### Additional Context:

react-color-palette/src/components/ColorPicker.component.tsx line 14

Great library, thank you!

**Comment by Wondermarin** [comment]
Thank you for your feedback ❤️, I will fix it in the next update.

**Comment by Wondermarin** [comment]
Should be fixed in 6.0.0
