### ISSUE TITLE
Allow empty hex color (transparent)

### ISSUE THREAD

**Issue by knaak2001** [Wondermarin/react-color-palette#16]
### The Problem:

Currently need a way to have the color picker be empty (or any transparent value) for hex indicating that it is transparent.

**Comment by knaak2001** [comment]
We have a current value empty ('') where the color palette and accept it as transparent.
As I could see on `toHex` util it returns fill style of canvas if hex value is empty.

some sort of allowing an empty value and color picker translate it as transparent

**Comment by Wondermarin** [comment]
But if you pass an empty string to `useColor` instead of a color, then you will get black in the output.
Isn't it better than transparent?

**Comment by Wondermarin** [comment]
If you clarify your enhancement you can re-open the issue.
