### ISSUE TITLE
get the color once the selection is finished, after a few seconds 

### ISSUE THREAD

**Issue by njavilas2015** [Wondermarin/react-color-palette#18]
Good night, some way to get the color once the selection is finished, the color obtained after a few seconds of having stopped changing the color .. I don't know if I explain myself well, sorry I'm a newbie

edit onBlur event

**Comment by Wondermarin** [comment]
> Sounds like he wants `onChangeCommitted` which fires with an `onMouseUp` event? I was looking for the same myself. I can debounce the onChange event, but I only want it to run when the user is finished dragging and releases the button.

Yes, I understand now.
I was thinking of adding an `onChangeComplete` event.

**Comment by Wondermarin** [comment]
Realised in [v6.2.0](https://github.com/Wondermarin/react-color-palette/releases/tag/v6.2.0)!
