### ISSUE TITLE
"Maximum update depth exceeded" with useColor

### ISSUE THREAD

**Issue by hug0b** [Wondermarin/react-color-palette#25]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| react-color-palette version | v6.1.0   |

### Expected Behavior:

`useColor` can accept a rgb or hsv initial color as documented

### Actual Behavior:

Using a color model that is not "hex" will trigger an infinite loop.

```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
```

### Additional Context:
Reproduced in this sandbox:

https://codesandbox.io/s/react-color-palette-infinite-loop-lzk0e?file=/src/App.tsx

**Comment by Wondermarin** [comment]
Fixed in [v6.2.0](https://github.com/Wondermarin/react-color-palette/releases/tag/v6.2.0)!
