### ISSUE TITLE
Wrong cursor position when opening palette

### ISSUE THREAD

**Issue by ju314ter** [Wondermarin/react-color-palette#31]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v12.22.0   |
| react-color-palette version | ^6.1.0   |

### Expected Behavior:

When opening a palette hooked to a color state and a color object, cursor should be positioned on the right color it has been hooked to

### Actual Behavior:

When opening the palette, the cursor is at the bottom left of the color picker (#000000 position)

**Comment by Wondermarin** [comment]
@ju314ter, attach a link to codesandbox.

**Comment by Wondermarin** [comment]
Outdated
