### ISSUE TITLE
Padding changes break the maximum slider value

### ISSUE THREAD

**Issue by rick-nu** [Wondermarin/react-color-palette#32]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v16   |
| react-color-palette version | v6.2.0   |
| Codesandbox.io | https://codesandbox.io/embed/spring-waterfall-v2673 |

### Expected Behavior:

The maximum value should not depend on padding/margin that is potentially changed.

### Actual Behavior:

The slider exceeds the maximum value when the vertical padding is removed. This will change "break" the maximum value:

```css
.rcp-body {
  padding-left: 0;
  padding-right: 0;
}
```

This is my implementation of the component were the padding is adjusted:
![](https://user-images.githubusercontent.com/6495166/140490258-42530041-b8b8-4093-b337-09929750e0bb.gif)

### Additional Context:

This ticket is a follow up from https://github.com/Wondermarin/react-color-palette/issues/23#issuecomment-981091864. Turns out there is a different reason why the maximum value was not working yet for me.

### Workaround:

Don't adjust the padding that are given for now.

**Comment by Wondermarin** [comment]
Duplicate #22
