### ISSUE TITLE
8 character hex alpha breaks slider at 0

### ISSUE THREAD

**Issue by frankie-swrve** [Wondermarin/react-color-palette#33]
### My Environment
MacOS 11.6 (2017 15-inch)
2.8ghz Quad-Core Intel Code i7
Radeon Pro 555 2GB / Intel HD 630 1536 MB

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v10.24.1   |
| react-color-palette version | v6.1.0   |

### Expected Behavior:
The slider should be at the zero position for an 8 character hex, i.e. #12345600

### Actual Behavior:
Slider resets to full position when alpha channel set to 0 via hex

### Additional Context:
Appears to be an issue with the HSV as a perfect 0 returns 'undefined' in the hsv.a position

**Comment by frankie-swrve** [comment]
Appears to also happen with RGB value.

So if you use the slider to set the value, the rgb.a and hsv.a will be set to 0, but when you open a pop up again with the same value, both will be undefined

**Comment by frankie-swrve** [comment]
```
  // Detect bad alpha value
  if (
    ((color.hex.length === 5 && color.hex.substring(4, 5) === '0') ||
      (color.hex.length === 9 && color.hex.substring(7, 9) === '00')) &&
    (color.rgb.a === undefined && color.hsv.a === undefined)
  ) {
    var _copy = color
    _copy.rgb.a = 0
    _copy.hsv.a = 0
    setColor(_copy)
  }
```

This solves the issue but I'd rather not have to detect this every time

**Comment by Wondermarin** [comment]
Fixed in v7
