### ISSUE TITLE
Updating the colour by typing in the hex input doesn't call onChangeComplete

### ISSUE THREAD

**Issue by peetjvv** [Wondermarin/react-color-palette#35]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v16.13.2   |
| react-color-palette version | v6.2.0   |

### Expected Behavior:

Changing the colour in the hex input should call the onChangeComplete callbackfn if the user entered a valid hex value.

### Actual Behavior:

Changing the colour in the hex input only calls the onChange callbackfn (even if the value entered is invalid) and not the onChangeComplete callbackfn.

### Additional Context:

For my use-case I only wrote this issue for the hex value, but I can imagine the same would apply for the RGB and HSL values.

**Comment by levikline** [comment]
@Wondermarin Are there plans to resolve this bug?

**Comment by Wondermarin** [comment]
Dropped in v7
