### ISSUE TITLE
onChangeComplete not invoking when pasting HEX code

### ISSUE THREAD

**Issue by csergiu** [Wondermarin/react-color-palette#40]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v14.19.1   |
| react-color-palette version | v6.1.0   |

### Expected Behavior:

`onChangeComplete` should be invoked after HEX color code input change

### Actual Behavior:

`onChangeComplete` doesn't get invoked

**Comment by CharlotteArai** [comment]
Hi! I'm having the same issue, did you find a solution? Thanks

**Comment by csergiu** [comment]
> Hi! I'm having the same issue, did you find a solution? Thanks

Yes, I ditched `onChangeComplete` and just wrapped the `onChange` callback in a debounce function.

**Comment by Wondermarin** [comment]
Duplicate #35
