### ISSUE TITLE
If the initial value passed to the useColor hook changes, it should reflect the same.

### ISSUE THREAD

**Issue by adityaxpique** [Wondermarin/react-color-palette#44]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v16.4.0   |
| react-color-palette version | v6.2.0  |

### Expected Behavior:

If the props change, the useColor hook should acknowledge that and the setColor function should be called once again to set the initial value according to the changed parameters.

### Actual Behavior:

If the initial value passed to the useColor hook changes, like in the case of passing props as initial value. The color does not update i.e. the hex value, the color and the position of the selector remain the same.

**Comment by gadzbi123** [comment]
The workaround to it (in React) is to make a useEffect to check if it has changed:
```ts
 const [color, setColor] = useColor("hex", "#000");
 useEffect(() => {
    setColor(toColor("hex", props.newColor) as Color);
  }, [props.newColor]);
```
This way if you change a passing value through parameter, it will changed the value on ColorPicker component:
```ts
 <ColorPicker
        width={500}
        height={200}
        color={color}
        onChange={setColor}
        dark
  />
```

**Comment by Wondermarin** [comment]
Duplicate #38
