### ISSUE TITLE
Might not works in react v17

### ISSUE THREAD

**Issue by restareaByWeezy** [Wondermarin/react-color-palette#47]
simple question: 
is this library works on react v17 or more?
cause I've recently upgraded react v17 and palette's css property: background-image got vanished.
<img width="408" alt="image" src="https://user-images.githubusercontent.com/64529155/190298460-072c9ca3-f7b7-4d67-8d1f-6b00c47577d2.png">

Is this issue relates with react version?

**Comment by DeveloperBlue** [comment]
I've run into the same issue, also on React 17. Unsure if it's a webpack or react issue

![electron_xliBx27QHM](https://user-images.githubusercontent.com/11480933/199979523-36dc1f78-1727-4d2e-987a-55125e628b3f.png)

**Comment by Wondermarin** [comment]
Should work in v7

**Comment by mikkark** [comment]
@restareaByWeezy Maybe you forgot to add import "react-color-palette/css" to your component? Omitting it seems to cause the behaviour you described.
