### ISSUE TITLE
Import error with toColor function and width property issue

### ISSUE THREAD

**Issue by samiwarraich** [Wondermarin/react-color-palette#57]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v18.12.1   |
| react-color-palette version | v7.0.2   |

Hello,

I am having an issue with importing the `toColor` function from the `react-color-palette`. The error message I am receiving is: `Attempted import error: 'toColor' is not exported from 'react-color-palette' (imported as 'toColor').`

Additionally, I am also encountering an issue with the `width` property. The error message I am receiving is: `Type error: Type '{ width: number; height: number; color: any; onChange: (color: any) => void; hideHSV: true; hideRGB: true; dark: true; }' is not assignable to type 'IntrinsicAttributes & IColorPickerProps'. Property 'width' does not exist on type 'IntrinsicAttributes & IColorPickerProps'.`

Thanks

```
23:33:33.097 | ./src/hooks/usePhoto.ts
23:33:33.097 | Attempted import error: 'toColor' is not exported from 'react-color-palette' (imported as 'toColor').
23:33:33.097 |  
23:33:33.097 | Import trace for requested module:
23:33:33.097 | ./src/hooks/usePhoto.ts
23:33:33.098 | ./src/hooks/index.ts
23:33:33.098 | ./src/components/ImageCard.tsx
23:33:33.098 |  
23:33:33.098 | - info Linting and checking validity of types...
23:33:36.308 | Failed to compile.
23:33:36.308 |  
23:33:36.308 | ./src/components/ColorPicker.tsx:17:7
23:33:36.308 | Type error: Type '{ width: number; height: number; color: any; onChange: (color: any) => void; hideHSV: true; hideRGB: true; dark: true; }' is not assignable to type 'IntrinsicAttributes & IColorPickerProps'.
23:33:36.308 | Property 'width' does not exist on type 'IntrinsicAttributes & IColorPickerProps'.
23:33:36.309 |  
23:33:36.309 | 15 \|   return (
23:33:36.309 | 16 \|     <RColorPicker
23:33:36.309 | > 17 \|       width={width}
23:33:36.309 | \|       ^
23:33:36.309 | 18 \|       height={190}
23:33:36.309 | 19 \|       color={color}
23:33:36.309 | 20 \|       onChange={setColor}
23:33:36.412 | error Command failed with exit code 1.
23:33:36.414 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
23:33:36.443 | Error: Command "yarn run build" exited with 1
```

**Comment by Wondermarin** [comment]
Hi! @samiwarraich 

Starting from v7, `<ColorPicker/>` component no longer has `width` prop. The component is now adaptive and fills in a parent element.

Also starting from v7, `toColor()` function has been replaced with `ColorService` - a more powerful way to interact with color than its predecessor.

You can read the [full changelist](https://github.com/Wondermarin/react-color-palette/releases/tag/v7.0.0) to be sure that you haven't missed anything.

You can also read [README.md](https://github.com/Wondermarin/react-color-palette/blob/main/README.md) with [usage examples](https://github.com/Wondermarin/react-color-palette#usage).
