### ISSUE TITLE
Not working with NextJS

### ISSUE THREAD

**Issue by ivan-dalmet** [Wondermarin/react-color-palette#6]
Hi I wanted to use your nice component in a NextJS app but it's not working 😉.

### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v14.15.4   |
| NextJS version             | v10.1.2  |
| react-color-palette version | v3.1.0   |

### Expected Behavior

Working with NextJS 😅

### Actual Behavior

Not working with NextJS 😅

![image](https://user-images.githubusercontent.com/9749061/113327510-58e90b80-931b-11eb-9bc7-05a7c47c5931.png)

https://nextjs.org/docs/messages/css-npm

### Idea of solution

Allow to import the ColorPicker without the CSS and the CSS separately. (You can keep the default export with everything 😉)
```
import { ColorPicker } from 'react-color-palette'
import 'react-color-palette/styles.css'
```

Hope this can help :) 
Thanks for maintaining an open source project!

**Comment by Wondermarin** [comment]
This will be fixed in the next update.

Thank you for your issue ❤️.

**Comment by Wondermarin** [comment]
In update 4.0.0 this should be resolved.

**Comment by ivan-dalmet** [comment]
It's working 🎉 Nice job! 
Thanks for the quick update 😊
