### ISSUE TITLE
ColorPicker/Saturation component doesn't support to be moved

### ISSUE THREAD

**Issue by msebire** [Wondermarin/react-color-palette#60]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v20.5.0   |
| react-color-palette version | v7.0.3   |

### Expected Behavior:

When in a scroll container (or a container that moved), the ColorPicker/Saturation component drag zone match what is on the screen.

### Actual Behavior:

When in a scrolled container, the drag zone stay the one we had during the first render.

### Additional Context:

The issue can be reproduced using https://codesandbox.io/s/competent-knuth-3mzv7d?file=/src/App.js

**Comment by Wondermarin** [comment]
@msebire, should be fixed in v7.0.4

**Comment by msebire** [comment]
It works, thanks a lot.
