### ISSUE TITLE
Reintroduction of Individual Visibility Control for Color Inputs

### ISSUE THREAD

**Issue by samiwarraich** [Wondermarin/react-color-palette#62]
### The Problem:

In the latest version of the react-color-palette library, the ability to individually control the visibility of each color input (RGBA, HEX, HSV) seems to have been removed. This feature was present in previous versions and was useful for scenarios where we wanted to show or hide individual color inputs based on certain conditions like color changes or user interactions.

### The Solution:

It would be beneficial to reintroduce this feature in the next version of the library. This could be implemented by adding new props to the color palette component: `hideRGB`, `hideHEX`, and `hideHSV`, each of which controls the visibility of the corresponding input. When `hideRGB` is `true`, the RGB input would be hidden, and so on for HEX and HSV.

### Additional Context:

The reintroduction of this feature would provide greater flexibility for users who want to customize the visibility of each color input in their color palette. It would be particularly useful in scenarios where some color inputs are not relevant or could potentially confuse the end user. For example, if a user is only interested in HEX colors, they could hide the RGB and HSV inputs to simplify the interface.

**Comment by Wondermarin** [comment]
@samiwarraich
I didn't introduce the `hideHEX`, `hideRGB` and `hideHSV` props so as not to make breaking changes and not release a major version. I changed the API a little and now in the `hideInput` prop you can specify an array of those fields that need to be hidden from UI. More information about the [new API](https://github.com/Wondermarin/react-color-palette#colorpicker-) can be found in the README, as well as an [example](https://github.com/Wondermarin/react-color-palette#hex-input-only) of its use.
