### ISSUE TITLE
Color Change using custom input feild

### ISSUE THREAD

**Issue by jimjacob29** [Wondermarin/react-color-palette#64]
Please give an option to setColor using a custom input feild of my choice

**Comment by Wondermarin** [comment]
Can you describe the problem in more detail?

**Comment by jimjacob29** [comment]
I have a requirement that requires a custom input feild which can take the hex value and change in the color picker. but I can't see any way to set the hex color directly to the setColor. for now it requires some custom calculations from my side to find out the rgb, hsv values and create the color object and set it back. So it is good to have a method to do the same just like the hook useColor is doing

**Comment by jimjacob29** [comment]
also it will be good to have some custom style acceptance as well

**Comment by Wondermarin** [comment]
> I have a requirement that requires a custom input feild which can take the hex value and change in the color picker. but I can't see any way to set the hex color directly to the setColor. for now it requires some custom calculations from my side to find out the rgb, hsv values and create the color object and set it back. So it is good to have a method to do the same just like the hook useColor is doing

`ColorService` is exported from the library, you can use it for custom color manipulation.

In your situation, you can use `ColorService.convert()` method, which takes 2 arguments: model and color (in the selected model), the result will return `IColor` object, which you can then pass to `setColor()`.
