### ISSUE TITLE
How to make Saturation transparent?

### ISSUE THREAD

**Issue by hasib-devs** [Wondermarin/react-color-palette#66]
![image](https://github.com/Wondermarin/react-color-palette/assets/102902562/df3e7726-30ec-4705-8264-ec9454a606fd)

**Comment by Wondermarin** [comment]
@hasib-devs, you can modify the `.rcp-saturation` class to suit your needs.

**Comment by hasib-devs** [comment]
> @hasib-devs, you can modify the `.rcp-saturation` class to suit your needs.

Have you ever tried it?
