### ISSUE TITLE
Cursor doesn't move to the end in the interactive component with modal

### ISSUE THREAD

**Issue by gembitious** [Wondermarin/react-color-palette#67]
Hi. I'm using react-color-palette with Popover component in MUI.
I place ColorPicker in the basic popover modal like the example below.
https://mui.com/material-ui/react-popover/#basic-popover

Then **cursor** in saturation and hue doesn't move to the right end.
See the maximum position of cursor I can drag in the image below.

![image](https://github.com/Wondermarin/react-color-palette/assets/66458976/a0666ba2-93f4-45b8-88e2-20aa1e97ef7a)

It seems that bug is caused by useBoundingClientRect hook in the code.

### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v18.17.1   |
| react-color-palette version | v7.1.0   |

**Comment by Wondermarin** [comment]
Can you attach an example?

**Comment by gembitious** [comment]
> Can you attach an example?

![react-color-palette-bug](https://github.com/Wondermarin/react-color-palette/assets/66458976/52cdf4bb-dad3-40c6-91f8-18d640ac8f5c)
Like this gif (dragging)

**Comment by Wondermarin** [comment]
I meant a link to codesandbox.

**Comment by windycloud** [comment]
I don't know if this issue has been fixed yet. I encountered this error, and the way I fixed it was on the first load of the Popover, I added a very small delay to allow the ColorPicker to load after the Popover has been loaded.

const [firstLoad, setFirstLoad] = useState(true);
useEffect(() => {
    if (open && firstLoad) {
      setTimeout(() => {
        setFirstLoad(false);
      }, 150);
    }
.............
{!firstLoad && (
        <ColorPicker ..../>
      )}

**Comment by windycloud** [comment]
I don't know if this issue has been fixed yet. I just encountered this error, and the way I fixed it was to add a very small delay each time the Popover is loaded, allowing the ColorPicker to load after the Popover has been loaded.

 const [delayLoad, setDelayLoad] = useState(true);
 useEffect(() => {
    if (open) {
      setTimeout(() => {
        setDelayLoad(false);
      }, 150);
    }
  }, [open]);

  const onClose = () => {
    handleClose();
    setDelayLoad(true);
  };
.........
.........
{!delayLoad && (
        <ColorPicker .... />
      )}

**Comment by faarda** [comment]
I can confirm that @windycloud's solution worked for me.

For just a bit of cleanup, it's easy to just do:

` useEffect(() => {
    setTimeout(() => {
      setDelayLoad(!modalShown);
    }, 500);
  }, [modalShown]);`

**Comment by Wondermarin** [comment]
Fixed in v7.2.1
