### ISSUE TITLE
Receiving error while test the application: "2d context not supported or canvas already initialized"

### ISSUE THREAD

**Issue by vmiroshn** [Wondermarin/react-color-palette#70]
### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| Node.JS version             | v18.17.0   |
| react-color-palette version | v7.1.0   |
| @testing-library/jest-dom version | v5.17.0   |
| jest-canvas-mock version | v2.5.2   |
| jest-junit version | v15.0.0   |

### Expected Behavior:

The color picker is used to select the background color for the selected entity. The entity is shown on the main screen, the color picker is rendered on the sidebar (I use semantic-ui-react widely in the project). When I test the sidebar appearing on clicking on a menu button, the test sees the sidebar, the color-picker on it, and the other HTML elements with the info received from props.

### Actual Behavior:

The test fails with the error message mentioned in the title of the request on the row with useColor initialization hook.

### Additional Context:

I made a setup of the jest-canvas-mock lib, as Google suggested.
I tried to place the color picker on the main page to check if the sidebar may use canvas as well and those two interfere with each other.
I still have the same error. Bear with me, if it is a well-known issue, I could not find it among the closed/opened list.

**Comment by Wondermarin** [comment]
Could you please provide a link to a CodeSandbox or StackBlitz example that reproduces the issue?

**Comment by vmiroshn** [comment]
> Could you please provide a link to a CodeSandbox or StackBlitz example that reproduces the issue?

I will. I need some free time to setup it.

**Comment by vmiroshn** [comment]
I pushed [here](https://github.com/vmiroshn/test-react-color-palette)

**Comment by Wondermarin** [comment]
I am closing this issue as it is not relevant to the `react-color-palette`.

<hr />

The `App.test.js` file mentions an issue with the canvas and suggests a possible solution.
```js
import { render, screen } from '@testing-library/react';
import App from './App';
// try solve the canvas issue in test <==
// import { setupJestCanvasMock } from 'jest-canvas-mock';

test('renders learn react link', () => {
  // try solve the canvas issue in test <==
  // jest.resetAllMocks();
  // setupJestCanvasMock();
  render(<App />);
  const linkElement = screen.getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});
```
Therefore, I would recommend you take a look at the `jest-canvas-mock` package.

**Comment by vmiroshn** [comment]
Thanks for your effort.
Could you comment on the additional minor issue:
https://github.com/vmiroshn/test-react-color-palette?tab=readme-ov-file#additional-issue
I added it initially in the readme, but haven't mentioned it here, I apologize for that.

**Comment by Wondermarin** [comment]
If the import of `react-color-palette/css` is not working for you, you can try using the direct path to the CSS file `react-color-palette/dist/css/rcp.css`.

**Comment by vmiroshn** [comment]
The solution to the issue - use hex format to initialize the useColor hook
`const [color, setColor] = useColor('#fff');`

The code like this causes the '2d context' error  while testing:
`const [color, setColor] = useColor('rgb(255, 255, 255, 0)');`
or
`const [color, setColor] = useColor('rgb(255, 255, 255)');`

This mock should be helpful as well:

```
class ResizeObserver {
  observe() {}
  unobserve() {}
  disconnect() {}
}

describe('Test title', () => {
  window.ResizeObserver = ResizeObserver;
```
