### ISSUE TITLE
[Bug] React-Color-Palette  does not support React Version 16

### ISSUE THREAD

**Issue by cmcWebCode40** [Wondermarin/react-color-palette#8]
Found this useful package and I'm having issues downloading it to work in my React version  v16.13.1

### My Environment

| Dependency                  | Version  |
| --------------------------- | -------- |
| React version                   |  v16.13.1 |
| Node.JS version             | v14.16.1   |
| react-color-palette version | v4.1.0   |

### Expected Behavior:

  To support React version 16 and above

## Error display while installation

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: admin-food-crowdy@0.1.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.13.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.1" from react-color-palette@4.1.0
npm ERR! node_modules/react-color-palette
npm ERR!   react-color-palette@"^4.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\hp\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Local\npm-cache\_logs\2021-04-22T11_59_33_775Z-debug.log`

**Comment by Wondermarin** [comment]
Thank you for your issue, this will be fixed in the next update.

**Comment by Wondermarin** [comment]
Should be fixed in 5.0.0
