### ISSUE TITLE
[Feature Request] Hope for interface that allows users to customize the style of the color palette.

### ISSUE THREAD

**Issue by ry-sun** [Wondermarin/react-color-palette#84]
### The Problem:

I’m really enjoying the color palette you provided, but it only has one preset style that doesn’t quite match my app’s theme. I was wondering if you could create an interface that allows users to customize the style of the color palette.

### The Solution:

 create an interface that allows users to customize the style of the color palette.

Alternatively, you could provide a light style option.

### Additional Context:

Right now, I’m using the !important property to override the styles, which is not very elegant or safe.

Here’s an example of how I’m currently using it:

```js
const ColorPickerWrapper = styled.div`
  .rcp {
    --rcp-background-color: ${({ theme }) => theme.background} !important;
    --rcp-field-input-color: ${({ theme }) => theme.text} !important;
    --rcp-field-input-border-color: ${({ theme }) => theme.border} !important;
    --rcp-field-label-color: ${({ theme }) => theme.label} !important;
  }
`;

return (
<ColorPickerWrapper>
  <ColorPicker height={200} color={color} onChange={setColor} hideHSV />
 </ColorPickerWrapper>
)
```

**Comment by paul-vd** [comment]
Agreed, and it would also be nice to have a light theme.

**Comment by Wondermarin** [comment]
I understand that working with styles can be tricky, but unfortunately, I can't suggest any improvements at the moment. Here are two workarounds you might try:
1. Use the `Saturation`, `Hue`, and `Alpha` components separately. This will give you more control over the appearance; however, you'll have to implement the color input logic yourself since the `Fields` component isn't exported separately.
2. Instead of importing styles from the package, you can provide your own using the same class names.

These options might not be the most elegant and could require some extra work on your part, but that's all I can offer for now. Starting with the next major release, the package will be distributed without built-in styles to enhance the developer experience, although I can't provide any timelines for that.

**Comment by rockmagma02** [comment]
Thanks for the explanation! Looking forward to your next major release.

**Comment by mickeys000** [comment]
> I understand that working with styles can be tricky, but unfortunately, I can't suggest any improvements at the moment. Here are two workarounds you might try:
> 
>     1. Use the `Saturation`, `Hue`, and `Alpha` components separately. This will give you more control over the appearance; however, you'll have to implement the color input logic yourself since the `Fields` component isn't exported separately.
> 
>     2. Instead of importing styles from the package, you can provide your own using the same class names.
> 
> 
> These options might not be the most elegant and could require some extra work on your part, but that's all I can offer for now. Starting with the next major release, the package will be distributed without built-in styles to enhance the developer experience, although I can't provide any timelines for that.

Apologies for commenting on an old closed issue, but I only had a quick question and didn't think it was worth opening a new one.
I was just wondering what would be the plan in terms of unlocking customisation. How much/what parts of the component(s) are you planning to have as customisable?

**Comment by Wondermarin** [comment]
> > I understand that working with styles can be tricky, but unfortunately, I can't suggest any improvements at the moment. Here are two workarounds you might try:
> > ```
> > 1. Use the `Saturation`, `Hue`, and `Alpha` components separately. This will give you more control over the appearance; however, you'll have to implement the color input logic yourself since the `Fields` component isn't exported separately.
> > 
> > 2. Instead of importing styles from the package, you can provide your own using the same class names.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These options might not be the most elegant and could require some extra work on your part, but that's all I can offer for now. Starting with the next major release, the package will be distributed without built-in styles to enhance the developer experience, although I can't provide any timelines for that.
> 
> Apologies for commenting on an old closed issue, but I only had a quick question and didn't think it was worth opening a new one. I was just wondering what would be the plan in terms of unlocking customisation. How much/what parts of the component(s) are you planning to have as customisable?

Version 8 will be a fully headless release, providing just the functionality to build your own color picker variations. I hope to release it this year, but I don't want to make any guarantees.
